# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41cc79d48ffd9931054fd812f93c2b256e12f09113658810dd45b93005f2dda26c45ad63812e413f82f928612576ebdf00ea67332a6f022e84b6fe681937c5ef

test:
  secret_key_base: 397543b26fd9e650f0edc5619b813e9b26087626df09e6136d71321020ffbb50b613c1c08c2ddd33040fe05f6d4d8da4dffe75c971e3453929861c52ec3540bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
